[package]
name = "rustbot"
version = "0.1.0"
authors = ["kangalioo", "technetos <mrgould93@gmail.com>"]
edition = "2018"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serenity = { git = "https://github.com/kangalioo/serenity", branch = "parse", default_features = false, features = ["rustls_backend", "builder", "cache", "client", "gateway", "model", "http"] }
serenity_framework = { path = "/home/kangalioo/dev/rust/_downloaded/serenity-framework/framework" }
reqwest = { version = "0.11", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
lazy_static = "1.4.0"
log = "0.4.0"
env_logger = "0.8.0"
envy = "0.4"
indexmap = "1.6"
strip-ansi-escapes = "0.1.0" # For normalizing godbolt responses
tokio = { version = "1.0", features = ["rt-multi-thread"] }
async-trait = "0.1.42"