[package]
name = "rustlang_discord_mod_bot"
version = "0.1.0"
authors = ["kangalioo", "technetos <mrgould93@gmail.com>"]
edition = "2018"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serenity = { version = "0.8.7", features = ["model"] }
reqwest = { version = "0.10", features = ["blocking", "json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
lazy_static = "1.4.0"
log = "0.4.0"
env_logger = "0.7.1"
envy = "0.4"
indexmap = "1.6"
serenity_framework = { path = "serenity-framework" }
strip-ansi-escapes = "0.1.0" # For normalizing godbolt responses